# Generated by Django 3.1.1 on 2021-02-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='year',
            field=models.IntegerField(verbose_name='Yıl'),
        ),
    ]
